import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {
  assessMaterialCompatibility,
  canonicalMaterial,
  materialsEquivalent,
  parseGcodeMaterialMetadata,
  readFileMaterialMetadata
} from '../src/file-material-metadata.js';

test('FlashForge G-code material parser prefers right_extruder_material metadata', () => {
  const parsed = parseGcodeMaterialMetadata(`; generated by OrcaSlicer\n; filament_type = PETG\n;right_extruder_material:ASA-CF\nG28\n`);
  assert.equal(parsed.metadataAvailable, true);
  assert.equal(parsed.requiredMaterial, 'ASA-CF');
  assert.deepEqual(parsed.materials, ['ASA-CF']);
  assert.equal(parsed.source, 'right_extruder_material');
});

test('material comparison treats punctuation variants as equivalent', () => {
  assert.equal(canonicalMaterial('ASA-CF'), 'ASACF');
  assert.equal(materialsEquivalent('ASA CF', 'asa_cf'), true);
  assert.equal(materialsEquivalent('PETG-CF', 'PETG'), false);
  assert.deepEqual(assessMaterialCompatibility('ASA_CF', { requiredMaterial:'ASA-CF' }), {
    comparable:true,
    mismatch:false,
    designatedMaterial:'ASA_CF',
    requiredMaterial:'ASA-CF'
  });
});

test('bounded local G-code reader finds slicer filament_type metadata near file tail', async () => {
  const dir = await mkdtemp(path.join(os.tmpdir(), 'pfc-material-test-'));
  const file = path.join(dir, 'part.gcode');
  try {
    await writeFile(file, `${'G1 X1 Y1\n'.repeat(5000)}; filament_type = PETG\n`);
    const parsed = await readFileMaterialMetadata(file, { maxChunkBytes:4096 });
    assert.equal(parsed.requiredMaterial, 'PETG');
  } finally {
    await rm(dir, { recursive:true, force:true });
  }
});

test('multiple distinct material types are recorded without inferring a single FlashForge requirement', () => {
  const parsed = parseGcodeMaterialMetadata('; filament_type = PLA;PETG\n');
  assert.equal(parsed.metadataAvailable, true);
  assert.equal(parsed.requiredMaterial, null);
  assert.deepEqual(parsed.materials, ['PLA', 'PETG']);
  assert.match(parsed.warning, /multiple filament types/i);
});
