import { EventEmitter } from 'node:events';
import crypto from 'node:crypto';
import { colorFamily, normalizeColor, normalizeColorFamily, representativeColor } from '../src/color-family.js';

const FINAL_STATES = new Set(['completed', 'cancelled', 'failed']);

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, Number(value) || 0));
}

function defaultTools(count) {
  const colors = ['#FF6B35', '#3A86FF', '#2EC4B6', '#F7C948'];
  return Array.from({ length: count }, (_, index) => ({
    index,
    actual: 25,
    target: 0,
    nozzleDiameter: 0.4,
    nozzleVolumeType: 'standard',
    offset: [0, 0, 0],
    filament: {
      present: true,
      material: 'PLA',
      materialVariant: null,
      color: colors[index % colors.length],
      vendor: 'Simulator',
      officialFilament: false,
      colorEditable: true
    }
  }));
}

function defaultAmsUnits(enabled) {
  if (!enabled) return [];
  const materials = [
    ['PLA', 'orange'], ['PLA', 'blue'], ['PETG', 'cyan'], ['ASA', 'yellow']
  ];
  return [{
    id:0,
    humidity:3,
    trays:materials.map(([material, colorFamilyValue], slotIndex) => ({
      slotIndex,
      present:true,
      material,
      materialVariant:null,
      colorFamily:colorFamilyValue,
      color:representativeColor(colorFamilyValue),
      vendor:'Simulator'
    }))
  }];
}

export class VirtualPrinter extends EventEmitter {
  constructor({ id, profile, name, host = '127.0.0.1', ports = {}, serialNumber, checkCode }) {
    super();
    this.id = id || `sim-${crypto.randomUUID().slice(0, 8)}`;
    this.profileId = profile.id;
    this.adapterType = profile.adapterType;
    this.manufacturer = profile.manufacturer;
    this.model = profile.model;
    this.name = name || `Simulated ${profile.model}`;
    this.host = host;
    this.ports = { ...ports };
    this.serialNumber = serialNumber || profile.defaults.serialNumber || `SIM-${this.id}`;
    this.checkCode = checkCode || profile.defaults.checkCode || 'SIMULATOR';
    this.online = true;
    this.status = 'idle';
    this.statusMessage = '';
    this.fileName = null;
    this.progress = 0;
    this.currentLayer = 0;
    this.totalLayers = 100;
    this.elapsedSeconds = 0;
    this.remainingSeconds = 0;
    this.durationSeconds = 600;
    this.speedMultiplier = 20;
    this.autoProgress = true;
    this.maintenanceEndsAt = 0;
    this.bed = { actual: 25, target: 0 };
    this.chamber = { actual: 25 };
    this.tools = defaultTools(profile.toolCount || 1);
    if (this.model === 'X1C') this.tools[0].nozzleVolumeType = 'hardened-steel';
    this.amsUnits = defaultAmsUnits(profile.adapterType === 'bambu-lab');
    this.externalSpool = { present:true, material:'PLA', materialVariant:null, colorFamily:'white', color:representativeColor('white'), vendor:'Simulator' };
    this.activeMaterialSource = this.amsUnits.length ? 0 : 254;
    this.fans = { cooling: 0, chamber: 0, internal: 0, external: 0 };
    this.files = new Map();
    this.history = [];
    this.faults = {
      responseDelayMs: 0,
      rejectNextCommand: false,
      malformedNextResponse: false,
      failVerification: false,
      retainFilename: false,
      stuckCancel: false,
      cameraUnavailable: false
    };
    this.logs = [];
    this.addFile('calibration-cube.gcode', {
      size: 2048,
      content: '; generated by Printer Emulator\n; filament_type = PLA\n; nozzle_diameter = 0.4\nG28\n'
    });
    this._lastTick = Date.now();
    this._timer = setInterval(() => this.tick(), 250);
    this._timer.unref?.();
    this.log('system', 'Virtual printer created');
  }

  close() {
    clearInterval(this._timer);
    this.removeAllListeners();
  }

  log(protocol, message, detail = null) {
    this.logs.unshift({ at: new Date().toISOString(), protocol, message, detail });
    if (this.logs.length > 300) this.logs.length = 300;
    this.emitChange();
  }

  emitChange() {
    this.emit('change', this.snapshot());
  }

  addFile(fileName, { size = 1024, content = '' } = {}) {
    const path = String(fileName || '').replace(/^\/+/, '').trim();
    if (!path) return;
    this.files.set(path, { path, size: Number(size) || 0, modified: Date.now() / 1000, content });
    this.emitChange();
  }

  removeFile(fileName) {
    this.files.delete(String(fileName || '').replace(/^\/+/, ''));
    this.emitChange();
  }

  startPrint(fileName) {
    const normalized = String(fileName || '').replace(/^\/+/, '').trim();
    if (!normalized) throw new Error('fileName is required');
    if (!this.files.has(normalized)) this.addFile(normalized);
    this.status = 'printing';
    this.statusMessage = '';
    this.fileName = normalized;
    this.progress = 0;
    this.currentLayer = 0;
    this.elapsedSeconds = 0;
    this.remainingSeconds = this.durationSeconds;
    this.log('state', `Started ${normalized}`);
  }

  action(action, values = {}) {
    const normalized = String(action || '').toLowerCase();
    if (normalized === 'start') return this.startPrint(values.fileName || this.files.keys().next().value);
    if (normalized === 'pause' && this.status === 'printing') this.status = 'paused';
    else if (normalized === 'resume' && this.status === 'paused') this.status = 'printing';
    else if (normalized === 'cancel') {
      this.status = 'cancelled';
      this.progress = clamp(this.progress, 0, 100);
      this.recordHistory('cancelled');
    } else if (normalized === 'complete') {
      this.status = 'completed';
      this.progress = 100;
      this.currentLayer = this.totalLayers;
      this.remainingSeconds = 0;
      this.recordHistory('completed');
    } else if (normalized === 'fail') {
      this.status = 'failed';
      this.statusMessage = values.message || 'Simulated printer failure';
      this.recordHistory('error');
    } else if (normalized === 'level') {
      this.status = 'leveling';
      this.statusMessage = 'Simulated bed levelling';
      this.fileName = null;
      this.maintenanceEndsAt = Date.now() + clamp(values.durationSeconds ?? 8, 1, 120) * 1000;
    } else if (normalized === 'idle') {
      this.status = 'idle';
      this.statusMessage = '';
      this.progress = 0;
      this.currentLayer = 0;
      if (!this.faults.retainFilename) this.fileName = null;
    } else if (normalized === 'offline') this.online = false;
    else if (normalized === 'online') this.online = true;
    else if (normalized === 'reset') this.reset();
    else if (!['pause', 'resume'].includes(normalized)) throw new Error(`Unsupported action: ${action}`);
    this.log('state', `Action: ${normalized}`);
  }

  reset() {
    this.online = true;
    this.status = 'idle';
    this.statusMessage = '';
    this.fileName = null;
    this.progress = 0;
    this.currentLayer = 0;
    this.elapsedSeconds = 0;
    this.remainingSeconds = 0;
    this.maintenanceEndsAt = 0;
    this.bed.target = 0;
    for (const tool of this.tools) tool.target = 0;
    for (const key of Object.keys(this.faults)) this.faults[key] = typeof this.faults[key] === 'boolean' ? false : 0;
    this.log('state', 'Printer reset');
  }

  recordHistory(status) {
    if (!this.fileName) return;
    this.history.unshift({ filename: this.fileName, status, start_time: Date.now() / 1000 - this.elapsedSeconds, end_time: Date.now() / 1000 });
    if (this.history.length > 100) this.history.length = 100;
  }

  configure(values = {}) {
    if (values.name !== undefined) this.name = String(values.name).trim() || this.name;
    if (values.online !== undefined) this.online = Boolean(values.online);
    if (values.status !== undefined) this.status = String(values.status).toLowerCase();
    if (values.progress !== undefined) this.progress = clamp(values.progress, 0, 100);
    if (values.durationSeconds !== undefined) this.durationSeconds = clamp(values.durationSeconds, 1, 864000);
    if (values.speedMultiplier !== undefined) this.speedMultiplier = clamp(values.speedMultiplier, 0.1, 1000);
    if (values.autoProgress !== undefined) this.autoProgress = Boolean(values.autoProgress);
    if (values.fileName !== undefined) this.fileName = values.fileName ? String(values.fileName) : null;
    if (values.bedTarget !== undefined) this.bed.target = clamp(values.bedTarget, 0, 150);
    if (values.toolTargets && typeof values.toolTargets === 'object') {
      for (const [index, target] of Object.entries(values.toolTargets)) {
        if (this.tools[Number(index)]) this.tools[Number(index)].target = clamp(target, 0, 400);
      }
    }
    if (values.amsUnits !== undefined) {
      const count = Math.round(clamp(values.amsUnits, 0, 4));
      const current = this.amsUnits;
      this.amsUnits = Array.from({ length:count }, (_, unitIndex) => current[unitIndex] || {
        id:unitIndex, humidity:3,
        trays:Array.from({ length:4 }, (_unused, slotIndex) => ({ slotIndex, present:false, material:null, materialVariant:null, colorFamily:null, color:null, vendor:'Simulator' }))
      });
      if (!this.amsUnits.length) this.activeMaterialSource = 254;
    }
    if (Array.isArray(values.amsSlots)) {
      for (const value of values.amsSlots) {
        const unitIndex = Number(value?.unitIndex);
        const slotIndex = Number(value?.slotIndex);
        const tray = this.amsUnits[unitIndex]?.trays?.[slotIndex];
        if (!tray) continue;
        if (value.present !== undefined) tray.present = Boolean(value.present);
        if (value.material !== undefined) tray.material = String(value.material || '').trim().toUpperCase() || null;
        if (value.colorFamily !== undefined) {
          tray.colorFamily = normalizeColorFamily(value.colorFamily);
          tray.color = representativeColor(tray.colorFamily);
        } else if (value.color !== undefined) {
          tray.color = normalizeColor(value.color);
          tray.colorFamily = colorFamily(tray.color);
        }
      }
    }
    if (values.externalSpool && typeof values.externalSpool === 'object') {
      const value = values.externalSpool;
      if (value.present !== undefined) this.externalSpool.present = Boolean(value.present);
      if (value.material !== undefined) this.externalSpool.material = String(value.material || '').trim().toUpperCase() || null;
      if (value.colorFamily !== undefined) {
        this.externalSpool.colorFamily = normalizeColorFamily(value.colorFamily);
        this.externalSpool.color = representativeColor(this.externalSpool.colorFamily);
      } else if (value.color !== undefined) {
        this.externalSpool.color = normalizeColor(value.color);
        this.externalSpool.colorFamily = colorFamily(this.externalSpool.color);
      }
    }
    if (values.activeMaterialSource !== undefined) {
      const source = Number(values.activeMaterialSource);
      if (source === 254 || (Number.isInteger(source) && source >= 0 && source < this.amsUnits.length * 4)) this.activeMaterialSource = source;
    }
    this.currentLayer = Math.round(this.totalLayers * this.progress / 100);
    this.log('state', 'Configuration updated');
  }

  setFaults(values = {}) {
    for (const key of Object.keys(this.faults)) {
      if (values[key] === undefined) continue;
      this.faults[key] = key === 'responseDelayMs' ? clamp(values[key], 0, 30000) : Boolean(values[key]);
    }
    this.log('fault', 'Fault configuration updated', { ...this.faults });
  }

  runScenario(name) {
    this.reset();
    const scenario = String(name || 'successful-print');
    if (scenario === 'successful-print') this.startPrint(this.files.keys().next().value);
    else if (scenario === 'cancel-retained-filename') {
      this.startPrint(this.files.keys().next().value);
      this.progress = 35;
      this.faults.retainFilename = true;
      this.faults.stuckCancel = true;
      this.action('cancel');
    } else if (scenario === 'upload-verification-failure') this.faults.failVerification = true;
    else if (scenario === 'offline') this.online = false;
    else if (scenario === 'material-mismatch') this.tools[0].filament.material = 'PETG';
    else if (scenario === 'nozzle-mismatch') this.tools[0].nozzleDiameter = 0.6;
    else throw new Error(`Unknown scenario: ${name}`);
    this.log('scenario', `Scenario loaded: ${scenario}`);
  }

  async beforeRequest(protocol, requestName) {
    this.log(protocol, requestName);
    if (!this.online) return { status: 503, body: { error: { message: 'Simulated printer is offline' } } };
    const delay = Number(this.faults.responseDelayMs || 0);
    if (delay) await new Promise((resolve) => setTimeout(resolve, delay));
    if (this.faults.rejectNextCommand) {
      this.faults.rejectNextCommand = false;
      this.emitChange();
      return { status: 500, body: { error: { message: 'Simulated command rejection' } } };
    }
    if (this.faults.malformedNextResponse) {
      this.faults.malformedNextResponse = false;
      this.emitChange();
      return { status: 200, raw: '{malformed response' };
    }
    return null;
  }

  tick(now = Date.now()) {
    const delta = Math.max(0, Math.min(5, (now - this._lastTick) / 1000));
    this._lastTick = now;
    const before = JSON.stringify({
      progress: Number(this.progress.toFixed(1)),
      bed: Number(this.bed.actual.toFixed(1)),
      tools: this.tools.map((tool) => Number(tool.actual.toFixed(1)))
    });
    const approach = (actual, target) => {
      const rate = target > actual ? 3 : 1.5;
      if (Math.abs(target - actual) < rate * delta) return target;
      return actual + Math.sign(target - actual) * rate * delta;
    };
    this.bed.actual = approach(this.bed.actual, this.bed.target || 25);
    for (const tool of this.tools) tool.actual = approach(tool.actual, tool.target || 25);

    if (this.status === 'leveling' && this.maintenanceEndsAt && now >= this.maintenanceEndsAt) {
      this.status = 'idle';
      this.statusMessage = '';
      this.maintenanceEndsAt = 0;
      this.log('state', 'Simulated bed levelling completed');
    }

    if (this.status === 'printing' && this.autoProgress) {
      this.elapsedSeconds += delta * this.speedMultiplier;
      this.progress = clamp(this.elapsedSeconds / this.durationSeconds * 100, 0, 100);
      this.currentLayer = Math.max(1, Math.round(this.totalLayers * this.progress / 100));
      this.remainingSeconds = Math.max(0, Math.round(this.durationSeconds - this.elapsedSeconds));
      if (this.progress >= 100) this.action('complete');
    }
    const after = JSON.stringify({
      progress: Number(this.progress.toFixed(1)),
      bed: Number(this.bed.actual.toFixed(1)),
      tools: this.tools.map((tool) => Number(tool.actual.toFixed(1)))
    });
    if (before !== after) this.emitChange();
  }

  snapshot({ includeLogs = true } = {}) {
    return {
      id: this.id,
      profileId: this.profileId,
      adapterType: this.adapterType,
      manufacturer: this.manufacturer,
      model: this.model,
      name: this.name,
      host: this.host,
      ports: { ...this.ports },
      serialNumber: this.serialNumber,
      checkCode: this.checkCode,
      online: this.online,
      status: this.status,
      statusMessage: this.statusMessage,
      fileName: this.fileName,
      progress: Number(this.progress.toFixed(1)),
      currentLayer: this.currentLayer,
      totalLayers: this.totalLayers,
      elapsedSeconds: Math.round(this.elapsedSeconds),
      remainingSeconds: Math.round(this.remainingSeconds),
      durationSeconds: this.durationSeconds,
      speedMultiplier: this.speedMultiplier,
      autoProgress: this.autoProgress,
      bed: { actual: Number(this.bed.actual.toFixed(1)), target: this.bed.target },
      chamber: { ...this.chamber },
      tools: this.tools.map((tool) => ({ ...tool, filament: { ...tool.filament }, offset: [...tool.offset] })),
      amsUnits:this.amsUnits.map((unit) => ({ ...unit, trays:unit.trays.map((tray) => ({ ...tray })) })),
      externalSpool:{ ...this.externalSpool },
      activeMaterialSource:this.activeMaterialSource,
      fans: { ...this.fans },
      files: [...this.files.values()].map(({ content, ...file }) => ({ ...file })),
      history: this.history.map((entry) => ({ ...entry })),
      faults: { ...this.faults },
      finalState: FINAL_STATES.has(this.status),
      ...(includeLogs ? { logs: this.logs.map((entry) => ({ ...entry })) } : {})
    };
  }
}
